# Generated by Django 4.2.1 on 2023-06-01 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0029_product_sort'),
        ('app_order', '0002_alter_orderitems_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app_catalog.product'),
            preserve_default=False,
        ),
    ]
