# Generated by Django 4.2.1 on 2023-06-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0006_order_delivery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('FREE', 'free'), ('PAID', 'paid')], default='FREE', max_length=4),
        ),
    ]
