# Generated by Django 4.2.1 on 2023-06-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0008_order_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('OC', 'online'), ('RA', 'random_account')], default='OC', max_length=2),
        ),
    ]
