# Generated by Django 4.2.1 on 2023-06-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0010_alter_order_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
