# Generated by Django 4.2.1 on 2023-06-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_basket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cart_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
