# Generated by Django 4.2.1 on 2023-06-01 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_basket', '0002_cartitem_cart_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
