# Generated by Django 4.2.1 on 2023-05-23 20:50

import app_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, null=True, upload_to=app_auth.models.profile_avatar_dir_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
