# Generated by Django 4.2.1 on 2023-05-23 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0006_avatar_remove_profile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='image',
            new_name='avatar',
        ),
    ]
