# Generated by Django 4.2.1 on 2023-05-23 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0007_rename_image_avatar_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_auth.avatar'),
            preserve_default=False,
        ),
    ]
