# Generated by Django 4.2.1 on 2023-05-28 17:18

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0007_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='app_catalog.category'),
            preserve_default=False,
        ),
    ]
