# Generated by Django 4.2.1 on 2023-05-29 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0011_productreviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreviews',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app_catalog.product'),
            preserve_default=False,
        ),
    ]
