# Generated by Django 4.2.1 on 2023-05-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0017_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
