# Generated by Django 4.2.1 on 2023-05-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0019_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='categories'),
        ),
    ]
