# Generated by Django 4.2.1 on 2023-05-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0020_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='products_limited',
            field=models.BooleanField(default=False),
        ),
    ]
