# Generated by Django 4.2.1 on 2023-06-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0023_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.ManyToManyField(null=True, to='app_catalog.specifications'),
        ),
    ]
