# Generated by Django 4.2.1 on 2023-06-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0024_product_specifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specifications',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='specifications',
            name='value',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
