# Generated by Django 4.2.1 on 2023-06-01 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0025_alter_specifications_name_alter_specifications_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='specifications',
        ),
    ]
