# Generated by Django 4.2.1 on 2023-06-01 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0026_remove_product_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='specifications',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='app_catalog.product'),
            preserve_default=False,
        ),
    ]
