# Generated by Django 4.2.1 on 2023-06-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0027_specifications_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specifications',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.ManyToManyField(null=True, to='app_catalog.specifications'),
        ),
    ]
