# Generated by Django 4.2.1 on 2023-06-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0028_remove_specifications_product_product_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sort',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
