# Generated by Django 4.2.1 on 2023-06-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0029_product_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.ManyToManyField(null=True, related_name='product', to='app_catalog.specifications'),
        ),
    ]
