# Generated by Django 4.2.1 on 2023-06-06 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0032_sales_remove_product_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='app_catalog.product'),
            preserve_default=False,
        ),
    ]
