# Generated by Django 4.2.1 on 2023-06-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0034_remove_sales_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='dateFrom',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sales',
            name='dateTo',
            field=models.DateTimeField(),
        ),
    ]
